### PR TITLE
remove unauthenticated uploads from the API (will be merged on {postponed again})

### PR DESCRIPTION
**Pull request by fishcakeday**
To combat spam and illegal uploads, we will deprecate unauthenticated uploads.

### CODE REVIEW

**Comment by TonyGiorgio** [comment]
I'm pretty sure we're using the pfp endpoint unauthenticated for mutiny profile image uploads. Need to double check with @benthecarman next week.

**Comment by joshuatbrown** [comment]
Nos is currently using unauthenticated uploads to `/api/v2/upload/files`. We'd appreciate a little bit of time to add auth.

**Comment by TonyGiorgio** [comment]
Mutiny has deployed this change.

**Comment by mplorentz** [comment]
@fishcakeday thank you. We deployed a production build of Nos that uses NIP-98 authentication today.

**Comment by v0l** [comment]
Yes

**Comment by mattn** [comment]
Currently, I have two bots posts images to nostr.build. But I don't mind you will change the APIs.

**Comment by syusui-s** [comment]
> @syusui-s are you using nip98 for uploads at https://rabbit.syusui.net/ ?

Thank you for letting me know. Rabbit doesn't support NIP-98 as for now. I will support NIP-98 soon.

> Do you know anyone else who might get affected?

I don't know... Most of all Japanese clients support NIP-98 as far as I know.

**Comment by mattn** [comment]
@fishcakeday Now I fixed two bots to use NIP-98.

**Comment by mattn** [comment]
BTW, nostr.build will be possible to delete image which was posted by same pubkey with NIP-98?

**Pull request merged**
